config/routes.rb
Uplate::Application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  
  match 'tickets' => 'pages#tickets', as: :tickets
  
  resources :clips, except: :show
  resources :photos, except: :show
  
  scope "contents" do
    get 'edit' => "contents#edit", as: :edit_contents
    put 'update' => "contents#update", as: :update_contents
  end
  
  root to: 'pages#home'
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  validates :video_embed_code, presence: true
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # HEROKU
  production = Rails.env == 'production'
  asset_path = production ? ":attachment" : "#{Rails.root}/public/:attachment/#{Rails.env}"
  has_attached_file :asset,
                    styles: { display: "800x800", thumb: "200x200" },
                    storage: production ? :s3 : :filesystem,
                    s3_credentials: { access_key_id: AppConfig["s3_key"], secret_access_key: AppConfig["s3_secret"] },
                    path: "#{asset_path}/:id/:style/:basename.:extension",
                    bucket: 'uplate'
  
  validates_attachment_presence :asset, if: 'new_record?'
  validates_attachment_content_type :asset, content_type: %r{(?:image)(?:\/.+)?}, message: "Only images are allowed.", if: 'new_record?'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :logged_in?
  def logged_in?
    cookies[:auth_token]
  end
  
  def require_login
  	return true if logged_in?
  	session[:return_to] = request.fullpath
  	redirect_to root_path, alert: "The requested page has restricted access." and return false
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_filter :require_login, except: :index
  before_filter :get_clip, only: [:edit, :update, :destroy]
  respond_to :html
  
  def index
    @clips = Clip.order("updated_at DESC").page(params[:page]).per(3)
  end
  
  def new
    @clip = Clip.new
  end
  
  def create
    @clip = Clip.new(params[:clip])
    flash[:notice] = "Clip added." if @clip.save
    respond_with @clip, location: clips_path
  end
  
  def update
    flash[:notice] = "Clip updated." if @clip.update_attributes(params[:clip])
    respond_with @clip, location: clips_path
  end
  
  def destroy
    flash[:notice] = "Clip removed." if @clip.destroy
    respond_with @clip
  end
  
  protected
    def get_clip
      @clip = Clip.find(params[:id])
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :require_login
  
  def edit
    @contents = Content.all
  end
  
  def update
    if @contents = Content.update(params[:contents].keys, params[:contents].values).reject { |c| c.errors.empty? }.empty?
      redirect_to root_path, notice: "Updated Contents"
    else
      render :edit
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController  
  def home
    @homepage_header          = Content.find_by_title('homepage_header').try(:content).to_s
    @promo_header             = Content.find_by_title("promo_header").try(:content).to_s
    @promo_video_embed_code   = Content.find_by_title("promo_video_embed_code").try(:content).to_s
    @promo_about              = Content.find_by_title("promo_about").try(:content).to_s
  end
  
  def tickets
    @tickets_content = Content.find_by_title("tickets").try(:content).to_s
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :require_login, except: :index
  before_filter :get_photo, only: [:edit, :update, :destroy]
  respond_to :html
  
  def index
    @photos = Photo.order('updated_at DESC')
  end
  
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(params[:photo])
    flash[:notice] = "Added photo" if @photo.save
    respond_with @photo, location: photos_path
  end
  
  def update
    flash[:notice] = "Updated photo" if @photo.update_attributes(params[:photo])
    respond_with @photo, location: photos_path
  end
  
  
  def destroy
    flash[:notice] = "Removed photo" if @photo.destroy
    respond_with @photo
  end
  
  private
    def get_photo
      @photo = Photo.find(params[:id])
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require 'digest/sha1'
    
  def create
    if Digest::SHA1.hexdigest(params[:username]) == USERNAME and Digest::SHA1.hexdigest(params[:password]) == PASSWORD
      cookies.permanent[:auth_token] = AppConfig["auth_token"]
      redirect_to root_path, notice: 'Logged in.'
    else
      redirect_to login_path, alert: "Wrong info."
    end
  end
  
  def destroy
    cookies.delete(:auth_token)
    redirect_to root_path, notice: "Logged out."
  end
  
  private
    USERNAME = AppConfig["admin_username"]
    PASSWORD = AppConfig["admin_password"]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_for_errors(object, options={})
    render partial: 'shared/form_errors', locals: options.merge!(object: object) if object.errors.any?
  end
  
  def no_records_check(records, name, options = {})
    options[:message] ||= "There are no #{name} to list."
    content_tag :div, options[:message], class: 'empty-list' if records.blank?
  end
  
  def edit_link(path)
    content_tag :span, class: "manage" do
      link_to "edit", path, class: 'edit-link'
    end if logged_in?
  end
  
  def create_link(object, path)
    content_tag :div, class: "manage" do
      link_to "new #{object}", path, class: 'create-link'
    end if logged_in?
  end
  
  def delete_link(object)
    content_tag :div, class: "manage" do
      link_to "delete #{object.class.to_s.downcase}", object, class: 'delete-link', method: 'delete', confirm: 'Are you sure?'
    end if logged_in?
  end
end

app/views/clips/_clip_form.html.erb
<%= form_for clip do |f| %>
  <%= check_for_errors clip %>
  <fieldset>
  <legend><%= title %></legend>
  <ol>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    
    <li>
      <%= f.label :video_embed_code %>
      <%= f.text_area :video_embed_code, size: '40x6' %>
    </li>

    <li>
      <%= f.label :description %>
      <%= f.text_area :description, size: "40x6" %>
    </li>
  </ol>
  </fieldset>
  <fieldset>
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/clips/edit.html.erb
<%= render partial: 'clip_form', locals: { clip: @clip, title: "Edit Clip" }%>
<%= delete_link @clip %>

app/views/clips/index.html.erb
<h2>Video Clips</h2>

<% for clip in @clips do %>
  <div class="clip">
    <h3><%= clip.title %></h3>
    <div class="video"><%= raw clip.video_embed_code || "No Video Available" %></div>
    <div class="description"><%= clip.description %></div>
    <%= edit_link edit_clip_path(clip) %>
  </div>
<% end %>

<%= paginate @clips %>
<%= no_records_check @clips, "Video Clips" %>

app/views/clips/new.html.erb
<%= render partial: 'clip_form', locals: { clip: @clip, title: "Add a Clip" } %>

app/views/contents/edit.html.erb
<%= form_tag update_contents_path, method: :put, class: "big" do %>
  <legend>Edit Contents</legend>

  <% @contents.each do |content| %>
    <%= check_for_errors content, object_name: "content" %>
    
    <fieldset class="content-fields">
      <%= fields_for "contents[]", content do |f| %>
        <h2><%= content.title.titleize %></h2>
        <%= f.text_area :content, size: "50x6", class: %w{promo_about tickets}.include?(content.title) ? 'ckeditor' : nil %>
      <% end %>
    </fieldset>
  <% end %>

  <fieldset>
    <%= submit_tag "Update Contents" %>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Up Late with Adam Fisher" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.ico" />
  <%= yield :head %>
</head>
<body>
  <div id="main">
    <div id="header">
      <nav id="nav">
        <%= link_to "Coming Up", root_path %>
        <%= link_to "Clips", clips_path %><br /><br />
        <%= link_to 'Photos', photos_path %>
        <%= link_to raw("Tickets &amp; Info"), tickets_path %>
      </nav>
    </div>

    <div class="top-info">
      <% unless flash.empty? %>
        <div id="flash">
          <% flash.each do |name, msg| %>
            <div class="<%= name %>"><%= msg %></div>
          <% end %>
        </div>
      <% end %>
      
      <% if logged_in? %>
        <div class="admin"><!--
          --><%= link_to 'manage contents', edit_contents_path %><!--
          --><%= link_to 'add clip', new_clip_path %><!--
          --><%= link_to 'add photo', new_photo_path %><!--
          --><%= link_to 'logout', logout_path %><!--
        --></div>
      <% end %>
    </div>
    
    <div id="content">
      <%= yield %>
    </div>
    
    <div id="adam">
      &nbsp;
    </div>
  </div> <!-- #main -->
</body>
</html>

app/views/pages/home.html.erb
<h2><%= @homepage_header %></h2>
<h3><%= @promo_header %><span class="spacer">&nbsp;</span><a href="https://twitter.com/share" class="twitter-share-button" data-text="<%=@promo_header%>" data-url="http://UpLateWithAdam.com" data-via="UpLateWithAdam">Tweet</a></h3>
<div class="video"><%= @promo_video_embed_code.html_safe %> </div>
<div class="promo-about"><%= @promo_about.html_safe %></div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/pages/tickets.html.erb
<h2>Tickets &amp; Info</h2>
<div id="tickets">
  <%= @tickets_content.html_safe %>
</div>

app/views/photos/_photo_form.html.erb
<%= form_for photo, html: { multipart: true } do |f| %>
  <%= check_for_errors photo %>
  <fieldset>
  <legend><%= title %></legend>
  <ol>
    <li>
      <%= f.label :asset, "File" %>
      <%= photo.new_record? ? f.file_field(:asset) : image_tag(photo.asset.url(:thumb)) %>
    </li>
    <li>
      <%= f.label :caption %>
      <%= f.text_field :caption %>
    </li>
  </ol>
  </fieldset>
  <fieldset>
    <%= f.submit title %>
  </fieldset>
<% end %>

app/views/photos/edit.html.erb
<%= render partial: 'photo_form', locals: { photo: @photo, title: "Edit Photo" }%>
<%= delete_link @photo %>

app/views/photos/index.html.erb
<h2>Photos</h2>
<% for photo in @photos do %>
  <div class="photo">
    <%= link_to image_tag(photo.asset.url(:thumb)), photo.asset.url(:display), class: 'lightbox', title: photo.caption %>
    <div class="caption"><%= photo.caption %></div>
    <%= edit_link edit_photo_path photo%>
  </div>
<% end %>

<%= no_records_check @photos, "Photos" %>

app/views/photos/new.html.erb
<%= render partial: 'photo_form', locals: { photo: @photo, title: "Add Photo" } %>

app/views/shared/_form_errors.html.erb
<fieldset>
  <legend>Errors</legend>
  <div id="error_explanation">
    <h2>Please fix the following <%= pluralize(object.errors.count, "error") %>: </h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</fieldset>